// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: course.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CourseAPI_GetCourse_FullMethodName         = "/course.v1.CourseAPI/GetCourse"
	CourseAPI_GetLesson_FullMethodName         = "/course.v1.CourseAPI/GetLesson"
	CourseAPI_GetLessons_FullMethodName        = "/course.v1.CourseAPI/GetLessons"
	CourseAPI_GetFocusedLessons_FullMethodName = "/course.v1.CourseAPI/GetFocusedLessons"
	CourseAPI_EnrollUser_FullMethodName        = "/course.v1.CourseAPI/EnrollUser"
	CourseAPI_GetUserProgress_FullMethodName   = "/course.v1.CourseAPI/GetUserProgress"
	CourseAPI_GetLessonState_FullMethodName    = "/course.v1.CourseAPI/GetLessonState"
	CourseAPI_AnswerCards_FullMethodName       = "/course.v1.CourseAPI/AnswerCards"
	CourseAPI_CreateCourse_FullMethodName      = "/course.v1.CourseAPI/CreateCourse"
	CourseAPI_CreateLesson_FullMethodName      = "/course.v1.CourseAPI/CreateLesson"
)

// CourseAPIClient is the client API for CourseAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CourseAPIClient interface {
	GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error)
	GetLesson(ctx context.Context, in *GetLessonRequest, opts ...grpc.CallOption) (*GetLessonResponse, error)
	GetLessons(ctx context.Context, in *GetLessonsRequest, opts ...grpc.CallOption) (*GetLessonsResponse, error)
	GetFocusedLessons(ctx context.Context, in *GetFocusedLessonsRequest, opts ...grpc.CallOption) (*GetFocusedLessonsResponse, error)
	EnrollUser(ctx context.Context, in *EnrollUserRequest, opts ...grpc.CallOption) (*EnrollUserResponse, error)
	GetUserProgress(ctx context.Context, in *GetUserProgressRequest, opts ...grpc.CallOption) (*GetUserProgressResponse, error)
	GetLessonState(ctx context.Context, in *GetLessonStateRequest, opts ...grpc.CallOption) (*GetLessonStateResponse, error)
	AnswerCards(ctx context.Context, in *AnswerCardsRequest, opts ...grpc.CallOption) (*AnswerCardsResponse, error)
	CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error)
	CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*CreateLessonResponse, error)
}

type courseAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCourseAPIClient(cc grpc.ClientConnInterface) CourseAPIClient {
	return &courseAPIClient{cc}
}

func (c *courseAPIClient) GetCourse(ctx context.Context, in *GetCourseRequest, opts ...grpc.CallOption) (*GetCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) GetLesson(ctx context.Context, in *GetLessonRequest, opts ...grpc.CallOption) (*GetLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLessonResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) GetLessons(ctx context.Context, in *GetLessonsRequest, opts ...grpc.CallOption) (*GetLessonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLessonsResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetLessons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) GetFocusedLessons(ctx context.Context, in *GetFocusedLessonsRequest, opts ...grpc.CallOption) (*GetFocusedLessonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFocusedLessonsResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetFocusedLessons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) EnrollUser(ctx context.Context, in *EnrollUserRequest, opts ...grpc.CallOption) (*EnrollUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollUserResponse)
	err := c.cc.Invoke(ctx, CourseAPI_EnrollUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) GetUserProgress(ctx context.Context, in *GetUserProgressRequest, opts ...grpc.CallOption) (*GetUserProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProgressResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetUserProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) GetLessonState(ctx context.Context, in *GetLessonStateRequest, opts ...grpc.CallOption) (*GetLessonStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLessonStateResponse)
	err := c.cc.Invoke(ctx, CourseAPI_GetLessonState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) AnswerCards(ctx context.Context, in *AnswerCardsRequest, opts ...grpc.CallOption) (*AnswerCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerCardsResponse)
	err := c.cc.Invoke(ctx, CourseAPI_AnswerCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) CreateCourse(ctx context.Context, in *CreateCourseRequest, opts ...grpc.CallOption) (*CreateCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCourseResponse)
	err := c.cc.Invoke(ctx, CourseAPI_CreateCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courseAPIClient) CreateLesson(ctx context.Context, in *CreateLessonRequest, opts ...grpc.CallOption) (*CreateLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLessonResponse)
	err := c.cc.Invoke(ctx, CourseAPI_CreateLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CourseAPIServer is the server API for CourseAPI service.
// All implementations should embed UnimplementedCourseAPIServer
// for forward compatibility.
type CourseAPIServer interface {
	GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error)
	GetLesson(context.Context, *GetLessonRequest) (*GetLessonResponse, error)
	GetLessons(context.Context, *GetLessonsRequest) (*GetLessonsResponse, error)
	GetFocusedLessons(context.Context, *GetFocusedLessonsRequest) (*GetFocusedLessonsResponse, error)
	EnrollUser(context.Context, *EnrollUserRequest) (*EnrollUserResponse, error)
	GetUserProgress(context.Context, *GetUserProgressRequest) (*GetUserProgressResponse, error)
	GetLessonState(context.Context, *GetLessonStateRequest) (*GetLessonStateResponse, error)
	AnswerCards(context.Context, *AnswerCardsRequest) (*AnswerCardsResponse, error)
	CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error)
	CreateLesson(context.Context, *CreateLessonRequest) (*CreateLessonResponse, error)
}

// UnimplementedCourseAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCourseAPIServer struct{}

func (UnimplementedCourseAPIServer) GetCourse(context.Context, *GetCourseRequest) (*GetCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCourse not implemented")
}
func (UnimplementedCourseAPIServer) GetLesson(context.Context, *GetLessonRequest) (*GetLessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLesson not implemented")
}
func (UnimplementedCourseAPIServer) GetLessons(context.Context, *GetLessonsRequest) (*GetLessonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLessons not implemented")
}
func (UnimplementedCourseAPIServer) GetFocusedLessons(context.Context, *GetFocusedLessonsRequest) (*GetFocusedLessonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFocusedLessons not implemented")
}
func (UnimplementedCourseAPIServer) EnrollUser(context.Context, *EnrollUserRequest) (*EnrollUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollUser not implemented")
}
func (UnimplementedCourseAPIServer) GetUserProgress(context.Context, *GetUserProgressRequest) (*GetUserProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProgress not implemented")
}
func (UnimplementedCourseAPIServer) GetLessonState(context.Context, *GetLessonStateRequest) (*GetLessonStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLessonState not implemented")
}
func (UnimplementedCourseAPIServer) AnswerCards(context.Context, *AnswerCardsRequest) (*AnswerCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnswerCards not implemented")
}
func (UnimplementedCourseAPIServer) CreateCourse(context.Context, *CreateCourseRequest) (*CreateCourseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCourse not implemented")
}
func (UnimplementedCourseAPIServer) CreateLesson(context.Context, *CreateLessonRequest) (*CreateLessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLesson not implemented")
}
func (UnimplementedCourseAPIServer) testEmbeddedByValue() {}

// UnsafeCourseAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CourseAPIServer will
// result in compilation errors.
type UnsafeCourseAPIServer interface {
	mustEmbedUnimplementedCourseAPIServer()
}

func RegisterCourseAPIServer(s grpc.ServiceRegistrar, srv CourseAPIServer) {
	// If the following call panics, it indicates UnimplementedCourseAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CourseAPI_ServiceDesc, srv)
}

func _CourseAPI_GetCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetCourse(ctx, req.(*GetCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_GetLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetLesson(ctx, req.(*GetLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_GetLessons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetLessons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetLessons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetLessons(ctx, req.(*GetLessonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_GetFocusedLessons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFocusedLessonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetFocusedLessons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetFocusedLessons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetFocusedLessons(ctx, req.(*GetFocusedLessonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_EnrollUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).EnrollUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_EnrollUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).EnrollUser(ctx, req.(*EnrollUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_GetUserProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetUserProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetUserProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetUserProgress(ctx, req.(*GetUserProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_GetLessonState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLessonStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).GetLessonState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_GetLessonState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).GetLessonState(ctx, req.(*GetLessonStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_AnswerCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).AnswerCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_AnswerCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).AnswerCards(ctx, req.(*AnswerCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_CreateCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).CreateCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_CreateCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).CreateCourse(ctx, req.(*CreateCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CourseAPI_CreateLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourseAPIServer).CreateLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CourseAPI_CreateLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourseAPIServer).CreateLesson(ctx, req.(*CreateLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CourseAPI_ServiceDesc is the grpc.ServiceDesc for CourseAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CourseAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "course.v1.CourseAPI",
	HandlerType: (*CourseAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourse",
			Handler:    _CourseAPI_GetCourse_Handler,
		},
		{
			MethodName: "GetLesson",
			Handler:    _CourseAPI_GetLesson_Handler,
		},
		{
			MethodName: "GetLessons",
			Handler:    _CourseAPI_GetLessons_Handler,
		},
		{
			MethodName: "GetFocusedLessons",
			Handler:    _CourseAPI_GetFocusedLessons_Handler,
		},
		{
			MethodName: "EnrollUser",
			Handler:    _CourseAPI_EnrollUser_Handler,
		},
		{
			MethodName: "GetUserProgress",
			Handler:    _CourseAPI_GetUserProgress_Handler,
		},
		{
			MethodName: "GetLessonState",
			Handler:    _CourseAPI_GetLessonState_Handler,
		},
		{
			MethodName: "AnswerCards",
			Handler:    _CourseAPI_AnswerCards_Handler,
		},
		{
			MethodName: "CreateCourse",
			Handler:    _CourseAPI_CreateCourse_Handler,
		},
		{
			MethodName: "CreateLesson",
			Handler:    _CourseAPI_CreateLesson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "course.proto",
}
