// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: course.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Order         int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Course) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Course) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Order         int64                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *Lesson) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Lesson) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Lesson) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Lesson) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Lesson) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Lesson) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Lesson) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type UserCourseProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId        string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CurrentLessonId string                 `protobuf:"bytes,4,opt,name=current_lesson_id,json=currentLessonId,proto3" json:"current_lesson_id,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"` // JSON string
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserCourseProgress) Reset() {
	*x = UserCourseProgress{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCourseProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCourseProgress) ProtoMessage() {}

func (x *UserCourseProgress) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCourseProgress.ProtoReflect.Descriptor instead.
func (*UserCourseProgress) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *UserCourseProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserCourseProgress) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCourseProgress) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UserCourseProgress) GetCurrentLessonId() string {
	if x != nil {
		return x.CurrentLessonId
	}
	return ""
}

func (x *UserCourseProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UserCourseProgress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserCourseProgress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HasPreviousPage bool                   `protobuf:"varint,1,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
	HasNextPage     bool                   `protobuf:"varint,2,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	StartCursor     string                 `protobuf:"bytes,3,opt,name=start_cursor,json=startCursor,proto3" json:"start_cursor,omitempty"`
	EndCursor       string                 `protobuf:"bytes,4,opt,name=end_cursor,json=endCursor,proto3" json:"end_cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *PageInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetStartCursor() string {
	if x != nil {
		return x.StartCursor
	}
	return ""
}

func (x *PageInfo) GetEndCursor() string {
	if x != nil {
		return x.EndCursor
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Last          int64                  `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
	First         int64                  `protobuf:"varint,2,opt,name=first,proto3" json:"first,omitempty"`
	After         string                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	Before        string                 `protobuf:"bytes,4,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetLast() int64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Pagination) GetFirst() int64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Pagination) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *Pagination) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

type LessonWithProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	IsCompleted   bool                   `protobuf:"varint,2,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,3,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonWithProgress) Reset() {
	*x = LessonWithProgress{}
	mi := &file_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonWithProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonWithProgress) ProtoMessage() {}

func (x *LessonWithProgress) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonWithProgress.ProtoReflect.Descriptor instead.
func (*LessonWithProgress) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{5}
}

func (x *LessonWithProgress) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

func (x *LessonWithProgress) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *LessonWithProgress) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type LessonsConnection struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Edges         []*LessonsConnection_Edge `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo                 `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonsConnection) Reset() {
	*x = LessonsConnection{}
	mi := &file_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonsConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonsConnection) ProtoMessage() {}

func (x *LessonsConnection) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonsConnection.ProtoReflect.Descriptor instead.
func (*LessonsConnection) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6}
}

func (x *LessonsConnection) GetEdges() []*LessonsConnection_Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *LessonsConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type LessonsWithProgressConnection struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Edges         []*LessonsWithProgressConnection_Edge `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo                             `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonsWithProgressConnection) Reset() {
	*x = LessonsWithProgressConnection{}
	mi := &file_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonsWithProgressConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonsWithProgressConnection) ProtoMessage() {}

func (x *LessonsWithProgressConnection) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonsWithProgressConnection.ProtoReflect.Descriptor instead.
func (*LessonsWithProgressConnection) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{7}
}

func (x *LessonsWithProgressConnection) GetEdges() []*LessonsWithProgressConnection_Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *LessonsWithProgressConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{8}
}

func (x *GetCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{9}
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type GetLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      string                 `protobuf:"bytes,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonRequest) Reset() {
	*x = GetLessonRequest{}
	mi := &file_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonRequest) ProtoMessage() {}

func (x *GetLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonRequest.ProtoReflect.Descriptor instead.
func (*GetLessonRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{10}
}

func (x *GetLessonRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

type GetLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonResponse) Reset() {
	*x = GetLessonResponse{}
	mi := &file_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonResponse) ProtoMessage() {}

func (x *GetLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonResponse.ProtoReflect.Descriptor instead.
func (*GetLessonResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{11}
}

func (x *GetLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // No user_id - this is public endpoint, returns Lesson without progress
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsRequest) Reset() {
	*x = GetLessonsRequest{}
	mi := &file_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsRequest) ProtoMessage() {}

func (x *GetLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsRequest.ProtoReflect.Descriptor instead.
func (*GetLessonsRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{12}
}

func (x *GetLessonsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetLessonsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetLessonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lessons       *LessonsConnection     `protobuf:"bytes,1,opt,name=lessons,proto3" json:"lessons,omitempty"` // Public - bare lessons
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonsResponse) Reset() {
	*x = GetLessonsResponse{}
	mi := &file_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonsResponse) ProtoMessage() {}

func (x *GetLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonsResponse.ProtoReflect.Descriptor instead.
func (*GetLessonsResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{13}
}

func (x *GetLessonsResponse) GetLessons() *LessonsConnection {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type GetFocusedLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // User context provided - returns LessonWithProgress
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFocusedLessonsRequest) Reset() {
	*x = GetFocusedLessonsRequest{}
	mi := &file_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFocusedLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFocusedLessonsRequest) ProtoMessage() {}

func (x *GetFocusedLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFocusedLessonsRequest.ProtoReflect.Descriptor instead.
func (*GetFocusedLessonsRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{14}
}

func (x *GetFocusedLessonsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetFocusedLessonsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetFocusedLessonsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetFocusedLessonsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Lessons       *LessonsWithProgressConnection `protobuf:"bytes,1,opt,name=lessons,proto3" json:"lessons,omitempty"` // Authenticated - with progress
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFocusedLessonsResponse) Reset() {
	*x = GetFocusedLessonsResponse{}
	mi := &file_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFocusedLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFocusedLessonsResponse) ProtoMessage() {}

func (x *GetFocusedLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFocusedLessonsResponse.ProtoReflect.Descriptor instead.
func (*GetFocusedLessonsResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{15}
}

func (x *GetFocusedLessonsResponse) GetLessons() *LessonsWithProgressConnection {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type EnrollUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollUserRequest) Reset() {
	*x = EnrollUserRequest{}
	mi := &file_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollUserRequest) ProtoMessage() {}

func (x *EnrollUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollUserRequest.ProtoReflect.Descriptor instead.
func (*EnrollUserRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{16}
}

func (x *EnrollUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollUserRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type EnrollUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollUserResponse) Reset() {
	*x = EnrollUserResponse{}
	mi := &file_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollUserResponse) ProtoMessage() {}

func (x *EnrollUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollUserResponse.ProtoReflect.Descriptor instead.
func (*EnrollUserResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{17}
}

func (x *EnrollUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressRequest) Reset() {
	*x = GetUserProgressRequest{}
	mi := &file_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressRequest) ProtoMessage() {}

func (x *GetUserProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressRequest.ProtoReflect.Descriptor instead.
func (*GetUserProgressRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProgressRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetUserProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      *UserCourseProgress    `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProgressResponse) Reset() {
	*x = GetUserProgressResponse{}
	mi := &file_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProgressResponse) ProtoMessage() {}

func (x *GetUserProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProgressResponse.ProtoReflect.Descriptor instead.
func (*GetUserProgressResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{19}
}

func (x *GetUserProgressResponse) GetProgress() *UserCourseProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type CardAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	AnswerId      string                 `protobuf:"bytes,2,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardAnswer) Reset() {
	*x = CardAnswer{}
	mi := &file_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardAnswer) ProtoMessage() {}

func (x *CardAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardAnswer.ProtoReflect.Descriptor instead.
func (*CardAnswer) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{20}
}

func (x *CardAnswer) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *CardAnswer) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

type AnswerCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,3,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	DeckId        string                 `protobuf:"bytes,4,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	CardAnswers   []*CardAnswer          `protobuf:"bytes,5,rep,name=card_answers,json=cardAnswers,proto3" json:"card_answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCardsRequest) Reset() {
	*x = AnswerCardsRequest{}
	mi := &file_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCardsRequest) ProtoMessage() {}

func (x *AnswerCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCardsRequest.ProtoReflect.Descriptor instead.
func (*AnswerCardsRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{21}
}

func (x *AnswerCardsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnswerCardsRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AnswerCardsRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *AnswerCardsRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *AnswerCardsRequest) GetCardAnswers() []*CardAnswer {
	if x != nil {
		return x.CardAnswers
	}
	return nil
}

type AnswerCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerCardsResponse) Reset() {
	*x = AnswerCardsResponse{}
	mi := &file_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerCardsResponse) ProtoMessage() {}

func (x *AnswerCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerCardsResponse.ProtoReflect.Descriptor instead.
func (*AnswerCardsResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{22}
}

func (x *AnswerCardsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{23}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{24}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type CreateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Order         int64                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_course_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{25}
}

func (x *CreateLessonRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateLessonRequest) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLessonRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_course_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{26}
}

func (x *CreateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type CardState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrectAnswers   int32                  `protobuf:"varint,1,opt,name=correct_answers,json=correctAnswers,proto3" json:"correct_answers,omitempty"`
	IncorrectAnswers int32                  `protobuf:"varint,2,opt,name=incorrect_answers,json=incorrectAnswers,proto3" json:"incorrect_answers,omitempty"`
	IsCompleted      bool                   `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CardState) Reset() {
	*x = CardState{}
	mi := &file_course_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardState) ProtoMessage() {}

func (x *CardState) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardState.ProtoReflect.Descriptor instead.
func (*CardState) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{27}
}

func (x *CardState) GetCorrectAnswers() int32 {
	if x != nil {
		return x.CorrectAnswers
	}
	return 0
}

func (x *CardState) GetIncorrectAnswers() int32 {
	if x != nil {
		return x.IncorrectAnswers
	}
	return 0
}

func (x *CardState) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *CardState) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type DeckState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         map[string]*CardState  `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsCompleted   bool                   `protobuf:"varint,2,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckState) Reset() {
	*x = DeckState{}
	mi := &file_course_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckState) ProtoMessage() {}

func (x *DeckState) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckState.ProtoReflect.Descriptor instead.
func (*DeckState) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{28}
}

func (x *DeckState) GetCards() map[string]*CardState {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *DeckState) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *DeckState) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type LessonState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decks         map[string]*DeckState  `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsCompleted   bool                   `protobuf:"varint,2,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonState) Reset() {
	*x = LessonState{}
	mi := &file_course_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonState) ProtoMessage() {}

func (x *LessonState) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonState.ProtoReflect.Descriptor instead.
func (*LessonState) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{29}
}

func (x *LessonState) GetDecks() map[string]*DeckState {
	if x != nil {
		return x.Decks
	}
	return nil
}

func (x *LessonState) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *LessonState) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetLessonStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	LessonId      string                 `protobuf:"bytes,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonStateRequest) Reset() {
	*x = GetLessonStateRequest{}
	mi := &file_course_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonStateRequest) ProtoMessage() {}

func (x *GetLessonStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonStateRequest.ProtoReflect.Descriptor instead.
func (*GetLessonStateRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{30}
}

func (x *GetLessonStateRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetLessonStateRequest) GetLessonId() string {
	if x != nil {
		return x.LessonId
	}
	return ""
}

func (x *GetLessonStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLessonStateResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	LessonState   map[string]*LessonState `protobuf:"bytes,1,rep,name=lesson_state,json=lessonState,proto3" json:"lesson_state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLessonStateResponse) Reset() {
	*x = GetLessonStateResponse{}
	mi := &file_course_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLessonStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLessonStateResponse) ProtoMessage() {}

func (x *GetLessonStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLessonStateResponse.ProtoReflect.Descriptor instead.
func (*GetLessonStateResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{31}
}

func (x *GetLessonStateResponse) GetLessonState() map[string]*LessonState {
	if x != nil {
		return x.LessonState
	}
	return nil
}

type LessonsConnection_Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Lesson                `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonsConnection_Edge) Reset() {
	*x = LessonsConnection_Edge{}
	mi := &file_course_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonsConnection_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonsConnection_Edge) ProtoMessage() {}

func (x *LessonsConnection_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonsConnection_Edge.ProtoReflect.Descriptor instead.
func (*LessonsConnection_Edge) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6, 0}
}

func (x *LessonsConnection_Edge) GetNode() *Lesson {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *LessonsConnection_Edge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type LessonsWithProgressConnection_Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *LessonWithProgress    `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonsWithProgressConnection_Edge) Reset() {
	*x = LessonsWithProgressConnection_Edge{}
	mi := &file_course_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonsWithProgressConnection_Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonsWithProgressConnection_Edge) ProtoMessage() {}

func (x *LessonsWithProgressConnection_Edge) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonsWithProgressConnection_Edge.ProtoReflect.Descriptor instead.
func (*LessonsWithProgressConnection_Edge) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{7, 0}
}

func (x *LessonsWithProgressConnection_Edge) GetNode() *LessonWithProgress {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *LessonsWithProgressConnection_Edge) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\tcourse.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x129\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xc6\x02\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x03R\x05order\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tedited_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x129\n" +
	"\n" +
	"deleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x92\x02\n" +
	"\x12UserCourseProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12*\n" +
	"\x11current_lesson_id\x18\x04 \x01(\tR\x0fcurrentLessonId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x01\n" +
	"\bPageInfo\x12*\n" +
	"\x11has_previous_page\x18\x01 \x01(\bR\x0fhasPreviousPage\x12\"\n" +
	"\rhas_next_page\x18\x02 \x01(\bR\vhasNextPage\x12!\n" +
	"\fstart_cursor\x18\x03 \x01(\tR\vstartCursor\x12\x1d\n" +
	"\n" +
	"end_cursor\x18\x04 \x01(\tR\tendCursor\"d\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04last\x18\x01 \x01(\x03R\x04last\x12\x14\n" +
	"\x05first\x18\x02 \x01(\x03R\x05first\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\x12\x16\n" +
	"\x06before\x18\x04 \x01(\tR\x06before\"\x81\x01\n" +
	"\x12LessonWithProgress\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.course.v1.LessonR\x06lesson\x12!\n" +
	"\fis_completed\x18\x02 \x01(\bR\visCompleted\x12\x1d\n" +
	"\n" +
	"is_current\x18\x03 \x01(\bR\tisCurrent\"\xc5\x01\n" +
	"\x11LessonsConnection\x127\n" +
	"\x05edges\x18\x01 \x03(\v2!.course.v1.LessonsConnection.EdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.course.v1.PageInfoR\bpageInfo\x1aE\n" +
	"\x04Edge\x12%\n" +
	"\x04node\x18\x01 \x01(\v2\x11.course.v1.LessonR\x04node\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\xe9\x01\n" +
	"\x1dLessonsWithProgressConnection\x12C\n" +
	"\x05edges\x18\x01 \x03(\v2-.course.v1.LessonsWithProgressConnection.EdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.course.v1.PageInfoR\bpageInfo\x1aQ\n" +
	"\x04Edge\x121\n" +
	"\x04node\x18\x01 \x01(\v2\x1d.course.v1.LessonWithProgressR\x04node\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"/\n" +
	"\x10GetCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\">\n" +
	"\x11GetCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course\"/\n" +
	"\x10GetLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\tR\blessonId\">\n" +
	"\x11GetLessonResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.course.v1.LessonR\x06lesson\"g\n" +
	"\x11GetLessonsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x125\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x15.course.v1.PaginationR\n" +
	"pagination\"L\n" +
	"\x12GetLessonsResponse\x126\n" +
	"\alessons\x18\x01 \x01(\v2\x1c.course.v1.LessonsConnectionR\alessons\"\x87\x01\n" +
	"\x18GetFocusedLessonsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x125\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x15.course.v1.PaginationR\n" +
	"pagination\"_\n" +
	"\x19GetFocusedLessonsResponse\x12B\n" +
	"\alessons\x18\x01 \x01(\v2(.course.v1.LessonsWithProgressConnectionR\alessons\"I\n" +
	"\x11EnrollUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\".\n" +
	"\x12EnrollUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x16GetUserProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"T\n" +
	"\x17GetUserProgressResponse\x129\n" +
	"\bprogress\x18\x01 \x01(\v2\x1d.course.v1.UserCourseProgressR\bprogress\"B\n" +
	"\n" +
	"CardAnswer\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\tR\x06cardId\x12\x1b\n" +
	"\tanswer_id\x18\x02 \x01(\tR\banswerId\"\xba\x01\n" +
	"\x12AnswerCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tlesson_id\x18\x03 \x01(\tR\blessonId\x12\x17\n" +
	"\adeck_id\x18\x04 \x01(\tR\x06deckId\x128\n" +
	"\fcard_answers\x18\x05 \x03(\v2\x15.course.v1.CardAnswerR\vcardAnswers\"/\n" +
	"\x13AnswerCardsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"A\n" +
	"\x14CreateCourseResponse\x12)\n" +
	"\x06course\x18\x01 \x01(\v2\x11.course.v1.CourseR\x06course\"\x94\x01\n" +
	"\x13CreateLessonRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x03R\x05order\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"A\n" +
	"\x14CreateLessonResponse\x12)\n" +
	"\x06lesson\x18\x01 \x01(\v2\x11.course.v1.LessonR\x06lesson\"\xc3\x01\n" +
	"\tCardState\x12'\n" +
	"\x0fcorrect_answers\x18\x01 \x01(\x05R\x0ecorrectAnswers\x12+\n" +
	"\x11incorrect_answers\x18\x02 \x01(\x05R\x10incorrectAnswers\x12!\n" +
	"\fis_completed\x18\x03 \x01(\bR\visCompleted\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xf4\x01\n" +
	"\tDeckState\x125\n" +
	"\x05cards\x18\x01 \x03(\v2\x1f.course.v1.DeckState.CardsEntryR\x05cards\x12!\n" +
	"\fis_completed\x18\x02 \x01(\bR\visCompleted\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1aN\n" +
	"\n" +
	"CardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.course.v1.CardStateR\x05value:\x028\x01\"\xf8\x01\n" +
	"\vLessonState\x127\n" +
	"\x05decks\x18\x01 \x03(\v2!.course.v1.LessonState.DecksEntryR\x05decks\x12!\n" +
	"\fis_completed\x18\x02 \x01(\bR\visCompleted\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x1aN\n" +
	"\n" +
	"DecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.course.v1.DeckStateR\x05value:\x028\x01\"j\n" +
	"\x15GetLessonStateRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\tR\blessonId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xc7\x01\n" +
	"\x16GetLessonStateResponse\x12U\n" +
	"\flesson_state\x18\x01 \x03(\v22.course.v1.GetLessonStateResponse.LessonStateEntryR\vlessonState\x1aV\n" +
	"\x10LessonStateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.course.v1.LessonStateR\x05value:\x028\x012\xc6\x06\n" +
	"\tCourseAPI\x12H\n" +
	"\tGetCourse\x12\x1b.course.v1.GetCourseRequest\x1a\x1c.course.v1.GetCourseResponse\"\x00\x12H\n" +
	"\tGetLesson\x12\x1b.course.v1.GetLessonRequest\x1a\x1c.course.v1.GetLessonResponse\"\x00\x12K\n" +
	"\n" +
	"GetLessons\x12\x1c.course.v1.GetLessonsRequest\x1a\x1d.course.v1.GetLessonsResponse\"\x00\x12`\n" +
	"\x11GetFocusedLessons\x12#.course.v1.GetFocusedLessonsRequest\x1a$.course.v1.GetFocusedLessonsResponse\"\x00\x12K\n" +
	"\n" +
	"EnrollUser\x12\x1c.course.v1.EnrollUserRequest\x1a\x1d.course.v1.EnrollUserResponse\"\x00\x12Z\n" +
	"\x0fGetUserProgress\x12!.course.v1.GetUserProgressRequest\x1a\".course.v1.GetUserProgressResponse\"\x00\x12W\n" +
	"\x0eGetLessonState\x12 .course.v1.GetLessonStateRequest\x1a!.course.v1.GetLessonStateResponse\"\x00\x12N\n" +
	"\vAnswerCards\x12\x1d.course.v1.AnswerCardsRequest\x1a\x1e.course.v1.AnswerCardsResponse\"\x00\x12Q\n" +
	"\fCreateCourse\x12\x1e.course.v1.CreateCourseRequest\x1a\x1f.course.v1.CreateCourseResponse\"\x00\x12Q\n" +
	"\fCreateLesson\x12\x1e.course.v1.CreateLessonRequest\x1a\x1f.course.v1.CreateLessonResponse\"\x00B0Z.github.com/XaviFP/toshokan/course/api/proto/v1b\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_course_proto_goTypes = []any{
	(*Course)(nil),                             // 0: course.v1.Course
	(*Lesson)(nil),                             // 1: course.v1.Lesson
	(*UserCourseProgress)(nil),                 // 2: course.v1.UserCourseProgress
	(*PageInfo)(nil),                           // 3: course.v1.PageInfo
	(*Pagination)(nil),                         // 4: course.v1.Pagination
	(*LessonWithProgress)(nil),                 // 5: course.v1.LessonWithProgress
	(*LessonsConnection)(nil),                  // 6: course.v1.LessonsConnection
	(*LessonsWithProgressConnection)(nil),      // 7: course.v1.LessonsWithProgressConnection
	(*GetCourseRequest)(nil),                   // 8: course.v1.GetCourseRequest
	(*GetCourseResponse)(nil),                  // 9: course.v1.GetCourseResponse
	(*GetLessonRequest)(nil),                   // 10: course.v1.GetLessonRequest
	(*GetLessonResponse)(nil),                  // 11: course.v1.GetLessonResponse
	(*GetLessonsRequest)(nil),                  // 12: course.v1.GetLessonsRequest
	(*GetLessonsResponse)(nil),                 // 13: course.v1.GetLessonsResponse
	(*GetFocusedLessonsRequest)(nil),           // 14: course.v1.GetFocusedLessonsRequest
	(*GetFocusedLessonsResponse)(nil),          // 15: course.v1.GetFocusedLessonsResponse
	(*EnrollUserRequest)(nil),                  // 16: course.v1.EnrollUserRequest
	(*EnrollUserResponse)(nil),                 // 17: course.v1.EnrollUserResponse
	(*GetUserProgressRequest)(nil),             // 18: course.v1.GetUserProgressRequest
	(*GetUserProgressResponse)(nil),            // 19: course.v1.GetUserProgressResponse
	(*CardAnswer)(nil),                         // 20: course.v1.CardAnswer
	(*AnswerCardsRequest)(nil),                 // 21: course.v1.AnswerCardsRequest
	(*AnswerCardsResponse)(nil),                // 22: course.v1.AnswerCardsResponse
	(*CreateCourseRequest)(nil),                // 23: course.v1.CreateCourseRequest
	(*CreateCourseResponse)(nil),               // 24: course.v1.CreateCourseResponse
	(*CreateLessonRequest)(nil),                // 25: course.v1.CreateLessonRequest
	(*CreateLessonResponse)(nil),               // 26: course.v1.CreateLessonResponse
	(*CardState)(nil),                          // 27: course.v1.CardState
	(*DeckState)(nil),                          // 28: course.v1.DeckState
	(*LessonState)(nil),                        // 29: course.v1.LessonState
	(*GetLessonStateRequest)(nil),              // 30: course.v1.GetLessonStateRequest
	(*GetLessonStateResponse)(nil),             // 31: course.v1.GetLessonStateResponse
	(*LessonsConnection_Edge)(nil),             // 32: course.v1.LessonsConnection.Edge
	(*LessonsWithProgressConnection_Edge)(nil), // 33: course.v1.LessonsWithProgressConnection.Edge
	nil,                           // 34: course.v1.DeckState.CardsEntry
	nil,                           // 35: course.v1.LessonState.DecksEntry
	nil,                           // 36: course.v1.GetLessonStateResponse.LessonStateEntry
	(*timestamppb.Timestamp)(nil), // 37: google.protobuf.Timestamp
}
var file_course_proto_depIdxs = []int32{
	37, // 0: course.v1.Course.created_at:type_name -> google.protobuf.Timestamp
	37, // 1: course.v1.Course.edited_at:type_name -> google.protobuf.Timestamp
	37, // 2: course.v1.Course.deleted_at:type_name -> google.protobuf.Timestamp
	37, // 3: course.v1.Lesson.created_at:type_name -> google.protobuf.Timestamp
	37, // 4: course.v1.Lesson.edited_at:type_name -> google.protobuf.Timestamp
	37, // 5: course.v1.Lesson.deleted_at:type_name -> google.protobuf.Timestamp
	37, // 6: course.v1.UserCourseProgress.created_at:type_name -> google.protobuf.Timestamp
	37, // 7: course.v1.UserCourseProgress.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: course.v1.LessonWithProgress.lesson:type_name -> course.v1.Lesson
	32, // 9: course.v1.LessonsConnection.edges:type_name -> course.v1.LessonsConnection.Edge
	3,  // 10: course.v1.LessonsConnection.page_info:type_name -> course.v1.PageInfo
	33, // 11: course.v1.LessonsWithProgressConnection.edges:type_name -> course.v1.LessonsWithProgressConnection.Edge
	3,  // 12: course.v1.LessonsWithProgressConnection.page_info:type_name -> course.v1.PageInfo
	0,  // 13: course.v1.GetCourseResponse.course:type_name -> course.v1.Course
	1,  // 14: course.v1.GetLessonResponse.lesson:type_name -> course.v1.Lesson
	4,  // 15: course.v1.GetLessonsRequest.pagination:type_name -> course.v1.Pagination
	6,  // 16: course.v1.GetLessonsResponse.lessons:type_name -> course.v1.LessonsConnection
	4,  // 17: course.v1.GetFocusedLessonsRequest.pagination:type_name -> course.v1.Pagination
	7,  // 18: course.v1.GetFocusedLessonsResponse.lessons:type_name -> course.v1.LessonsWithProgressConnection
	2,  // 19: course.v1.GetUserProgressResponse.progress:type_name -> course.v1.UserCourseProgress
	20, // 20: course.v1.AnswerCardsRequest.card_answers:type_name -> course.v1.CardAnswer
	0,  // 21: course.v1.CreateCourseResponse.course:type_name -> course.v1.Course
	1,  // 22: course.v1.CreateLessonResponse.lesson:type_name -> course.v1.Lesson
	37, // 23: course.v1.CardState.completed_at:type_name -> google.protobuf.Timestamp
	34, // 24: course.v1.DeckState.cards:type_name -> course.v1.DeckState.CardsEntry
	37, // 25: course.v1.DeckState.completed_at:type_name -> google.protobuf.Timestamp
	35, // 26: course.v1.LessonState.decks:type_name -> course.v1.LessonState.DecksEntry
	37, // 27: course.v1.LessonState.completed_at:type_name -> google.protobuf.Timestamp
	36, // 28: course.v1.GetLessonStateResponse.lesson_state:type_name -> course.v1.GetLessonStateResponse.LessonStateEntry
	1,  // 29: course.v1.LessonsConnection.Edge.node:type_name -> course.v1.Lesson
	5,  // 30: course.v1.LessonsWithProgressConnection.Edge.node:type_name -> course.v1.LessonWithProgress
	27, // 31: course.v1.DeckState.CardsEntry.value:type_name -> course.v1.CardState
	28, // 32: course.v1.LessonState.DecksEntry.value:type_name -> course.v1.DeckState
	29, // 33: course.v1.GetLessonStateResponse.LessonStateEntry.value:type_name -> course.v1.LessonState
	8,  // 34: course.v1.CourseAPI.GetCourse:input_type -> course.v1.GetCourseRequest
	10, // 35: course.v1.CourseAPI.GetLesson:input_type -> course.v1.GetLessonRequest
	12, // 36: course.v1.CourseAPI.GetLessons:input_type -> course.v1.GetLessonsRequest
	14, // 37: course.v1.CourseAPI.GetFocusedLessons:input_type -> course.v1.GetFocusedLessonsRequest
	16, // 38: course.v1.CourseAPI.EnrollUser:input_type -> course.v1.EnrollUserRequest
	18, // 39: course.v1.CourseAPI.GetUserProgress:input_type -> course.v1.GetUserProgressRequest
	30, // 40: course.v1.CourseAPI.GetLessonState:input_type -> course.v1.GetLessonStateRequest
	21, // 41: course.v1.CourseAPI.AnswerCards:input_type -> course.v1.AnswerCardsRequest
	23, // 42: course.v1.CourseAPI.CreateCourse:input_type -> course.v1.CreateCourseRequest
	25, // 43: course.v1.CourseAPI.CreateLesson:input_type -> course.v1.CreateLessonRequest
	9,  // 44: course.v1.CourseAPI.GetCourse:output_type -> course.v1.GetCourseResponse
	11, // 45: course.v1.CourseAPI.GetLesson:output_type -> course.v1.GetLessonResponse
	13, // 46: course.v1.CourseAPI.GetLessons:output_type -> course.v1.GetLessonsResponse
	15, // 47: course.v1.CourseAPI.GetFocusedLessons:output_type -> course.v1.GetFocusedLessonsResponse
	17, // 48: course.v1.CourseAPI.EnrollUser:output_type -> course.v1.EnrollUserResponse
	19, // 49: course.v1.CourseAPI.GetUserProgress:output_type -> course.v1.GetUserProgressResponse
	31, // 50: course.v1.CourseAPI.GetLessonState:output_type -> course.v1.GetLessonStateResponse
	22, // 51: course.v1.CourseAPI.AnswerCards:output_type -> course.v1.AnswerCardsResponse
	24, // 52: course.v1.CourseAPI.CreateCourse:output_type -> course.v1.CreateCourseResponse
	26, // 53: course.v1.CourseAPI.CreateLesson:output_type -> course.v1.CreateLessonResponse
	44, // [44:54] is the sub-list for method output_type
	34, // [34:44] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
