// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: deck.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecksAPI_GetDeck_FullMethodName         = "/deck.v1.DecksAPI/GetDeck"
	DecksAPI_GetDecks_FullMethodName        = "/deck.v1.DecksAPI/GetDecks"
	DecksAPI_CreateDeck_FullMethodName      = "/deck.v1.DecksAPI/CreateDeck"
	DecksAPI_DeleteDeck_FullMethodName      = "/deck.v1.DecksAPI/DeleteDeck"
	DecksAPI_GetPopularDecks_FullMethodName = "/deck.v1.DecksAPI/GetPopularDecks"
	DecksAPI_CreateCard_FullMethodName      = "/deck.v1.DecksAPI/CreateCard"
	DecksAPI_GetCards_FullMethodName        = "/deck.v1.DecksAPI/GetCards"
)

// DecksAPIClient is the client API for DecksAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecksAPIClient interface {
	GetDeck(ctx context.Context, in *GetDeckRequest, opts ...grpc.CallOption) (*GetDeckResponse, error)
	GetDecks(ctx context.Context, in *GetDecksRequest, opts ...grpc.CallOption) (*GetDecksResponse, error)
	CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...grpc.CallOption) (*CreateDeckResponse, error)
	DeleteDeck(ctx context.Context, in *DeleteDeckRequest, opts ...grpc.CallOption) (*DeleteDeckResponse, error)
	GetPopularDecks(ctx context.Context, in *GetPopularDecksRequest, opts ...grpc.CallOption) (*GetPopularDecksResponse, error)
	CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error)
	GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error)
}

type decksAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewDecksAPIClient(cc grpc.ClientConnInterface) DecksAPIClient {
	return &decksAPIClient{cc}
}

func (c *decksAPIClient) GetDeck(ctx context.Context, in *GetDeckRequest, opts ...grpc.CallOption) (*GetDeckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeckResponse)
	err := c.cc.Invoke(ctx, DecksAPI_GetDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) GetDecks(ctx context.Context, in *GetDecksRequest, opts ...grpc.CallOption) (*GetDecksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDecksResponse)
	err := c.cc.Invoke(ctx, DecksAPI_GetDecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) CreateDeck(ctx context.Context, in *CreateDeckRequest, opts ...grpc.CallOption) (*CreateDeckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeckResponse)
	err := c.cc.Invoke(ctx, DecksAPI_CreateDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) DeleteDeck(ctx context.Context, in *DeleteDeckRequest, opts ...grpc.CallOption) (*DeleteDeckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeckResponse)
	err := c.cc.Invoke(ctx, DecksAPI_DeleteDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) GetPopularDecks(ctx context.Context, in *GetPopularDecksRequest, opts ...grpc.CallOption) (*GetPopularDecksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPopularDecksResponse)
	err := c.cc.Invoke(ctx, DecksAPI_GetPopularDecks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) CreateCard(ctx context.Context, in *CreateCardRequest, opts ...grpc.CallOption) (*CreateCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCardResponse)
	err := c.cc.Invoke(ctx, DecksAPI_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decksAPIClient) GetCards(ctx context.Context, in *GetCardsRequest, opts ...grpc.CallOption) (*GetCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardsResponse)
	err := c.cc.Invoke(ctx, DecksAPI_GetCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecksAPIServer is the server API for DecksAPI service.
// All implementations should embed UnimplementedDecksAPIServer
// for forward compatibility.
type DecksAPIServer interface {
	GetDeck(context.Context, *GetDeckRequest) (*GetDeckResponse, error)
	GetDecks(context.Context, *GetDecksRequest) (*GetDecksResponse, error)
	CreateDeck(context.Context, *CreateDeckRequest) (*CreateDeckResponse, error)
	DeleteDeck(context.Context, *DeleteDeckRequest) (*DeleteDeckResponse, error)
	GetPopularDecks(context.Context, *GetPopularDecksRequest) (*GetPopularDecksResponse, error)
	CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error)
	GetCards(context.Context, *GetCardsRequest) (*GetCardsResponse, error)
}

// UnimplementedDecksAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecksAPIServer struct{}

func (UnimplementedDecksAPIServer) GetDeck(context.Context, *GetDeckRequest) (*GetDeckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeck not implemented")
}
func (UnimplementedDecksAPIServer) GetDecks(context.Context, *GetDecksRequest) (*GetDecksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecks not implemented")
}
func (UnimplementedDecksAPIServer) CreateDeck(context.Context, *CreateDeckRequest) (*CreateDeckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeck not implemented")
}
func (UnimplementedDecksAPIServer) DeleteDeck(context.Context, *DeleteDeckRequest) (*DeleteDeckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDeck not implemented")
}
func (UnimplementedDecksAPIServer) GetPopularDecks(context.Context, *GetPopularDecksRequest) (*GetPopularDecksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPopularDecks not implemented")
}
func (UnimplementedDecksAPIServer) CreateCard(context.Context, *CreateCardRequest) (*CreateCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedDecksAPIServer) GetCards(context.Context, *GetCardsRequest) (*GetCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCards not implemented")
}
func (UnimplementedDecksAPIServer) testEmbeddedByValue() {}

// UnsafeDecksAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecksAPIServer will
// result in compilation errors.
type UnsafeDecksAPIServer interface {
	mustEmbedUnimplementedDecksAPIServer()
}

func RegisterDecksAPIServer(s grpc.ServiceRegistrar, srv DecksAPIServer) {
	// If the following call panics, it indicates UnimplementedDecksAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecksAPI_ServiceDesc, srv)
}

func _DecksAPI_GetDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).GetDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_GetDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).GetDeck(ctx, req.(*GetDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_GetDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).GetDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_GetDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).GetDecks(ctx, req.(*GetDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_CreateDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).CreateDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_CreateDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).CreateDeck(ctx, req.(*CreateDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_DeleteDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).DeleteDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_DeleteDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).DeleteDeck(ctx, req.(*DeleteDeckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_GetPopularDecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPopularDecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).GetPopularDecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_GetPopularDecks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).GetPopularDecks(ctx, req.(*GetPopularDecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).CreateCard(ctx, req.(*CreateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecksAPI_GetCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecksAPIServer).GetCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecksAPI_GetCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecksAPIServer).GetCards(ctx, req.(*GetCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DecksAPI_ServiceDesc is the grpc.ServiceDesc for DecksAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecksAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deck.v1.DecksAPI",
	HandlerType: (*DecksAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeck",
			Handler:    _DecksAPI_GetDeck_Handler,
		},
		{
			MethodName: "GetDecks",
			Handler:    _DecksAPI_GetDecks_Handler,
		},
		{
			MethodName: "CreateDeck",
			Handler:    _DecksAPI_CreateDeck_Handler,
		},
		{
			MethodName: "DeleteDeck",
			Handler:    _DecksAPI_DeleteDeck_Handler,
		},
		{
			MethodName: "GetPopularDecks",
			Handler:    _DecksAPI_GetPopularDecks_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _DecksAPI_CreateCard_Handler,
		},
		{
			MethodName: "GetCards",
			Handler:    _DecksAPI_GetCards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deck.proto",
}
