// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: dealer.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckId        string                 `protobuf:"bytes,2,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	NumberOfCards uint32                 `protobuf:"varint,3,opt,name=number_of_cards,json=numberOfCards,proto3" json:"number_of_cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealRequest) Reset() {
	*x = DealRequest{}
	mi := &file_dealer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealRequest) ProtoMessage() {}

func (x *DealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealRequest.ProtoReflect.Descriptor instead.
func (*DealRequest) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{0}
}

func (x *DealRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DealRequest) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *DealRequest) GetNumberOfCards() uint32 {
	if x != nil {
		return x.NumberOfCards
	}
	return 0
}

type DealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardIds       []string               `protobuf:"bytes,1,rep,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DealResponse) Reset() {
	*x = DealResponse{}
	mi := &file_dealer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DealResponse) ProtoMessage() {}

func (x *DealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DealResponse.ProtoReflect.Descriptor instead.
func (*DealResponse) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{1}
}

func (x *DealResponse) GetCardIds() []string {
	if x != nil {
		return x.CardIds
	}
	return nil
}

type StoreAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnswerIds     []string               `protobuf:"bytes,2,rep,name=answer_ids,json=answerIds,proto3" json:"answer_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreAnswersRequest) Reset() {
	*x = StoreAnswersRequest{}
	mi := &file_dealer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAnswersRequest) ProtoMessage() {}

func (x *StoreAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAnswersRequest.ProtoReflect.Descriptor instead.
func (*StoreAnswersRequest) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{2}
}

func (x *StoreAnswersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreAnswersRequest) GetAnswerIds() []string {
	if x != nil {
		return x.AnswerIds
	}
	return nil
}

type StoreAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreAnswersResponse) Reset() {
	*x = StoreAnswersResponse{}
	mi := &file_dealer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreAnswersResponse) ProtoMessage() {}

func (x *StoreAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dealer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreAnswersResponse.ProtoReflect.Descriptor instead.
func (*StoreAnswersResponse) Descriptor() ([]byte, []int) {
	return file_dealer_proto_rawDescGZIP(), []int{3}
}

var File_dealer_proto protoreflect.FileDescriptor

const file_dealer_proto_rawDesc = "" +
	"\n" +
	"\fdealer.proto\x12\x02v1\"g\n" +
	"\vDealRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\adeck_id\x18\x02 \x01(\tR\x06deckId\x12&\n" +
	"\x0fnumber_of_cards\x18\x03 \x01(\rR\rnumberOfCards\")\n" +
	"\fDealResponse\x12\x19\n" +
	"\bcard_ids\x18\x01 \x03(\tR\acardIds\"M\n" +
	"\x13StoreAnswersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"answer_ids\x18\x02 \x03(\tR\tanswerIds\"\x16\n" +
	"\x14StoreAnswersResponse2v\n" +
	"\x06Dealer\x12)\n" +
	"\x04Deal\x12\x0f.v1.DealRequest\x1a\x10.v1.DealResponse\x12A\n" +
	"\fStoreAnswers\x12\x17.v1.StoreAnswersRequest\x1a\x18.v1.StoreAnswersResponseB0Z.github.com/XaviFP/toshokan/dealer/api/proto/v1b\x06proto3"

var (
	file_dealer_proto_rawDescOnce sync.Once
	file_dealer_proto_rawDescData []byte
)

func file_dealer_proto_rawDescGZIP() []byte {
	file_dealer_proto_rawDescOnce.Do(func() {
		file_dealer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dealer_proto_rawDesc), len(file_dealer_proto_rawDesc)))
	})
	return file_dealer_proto_rawDescData
}

var file_dealer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dealer_proto_goTypes = []any{
	(*DealRequest)(nil),          // 0: v1.DealRequest
	(*DealResponse)(nil),         // 1: v1.DealResponse
	(*StoreAnswersRequest)(nil),  // 2: v1.StoreAnswersRequest
	(*StoreAnswersResponse)(nil), // 3: v1.StoreAnswersResponse
}
var file_dealer_proto_depIdxs = []int32{
	0, // 0: v1.Dealer.Deal:input_type -> v1.DealRequest
	2, // 1: v1.Dealer.StoreAnswers:input_type -> v1.StoreAnswersRequest
	1, // 2: v1.Dealer.Deal:output_type -> v1.DealResponse
	3, // 3: v1.Dealer.StoreAnswers:output_type -> v1.StoreAnswersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dealer_proto_init() }
func file_dealer_proto_init() {
	if File_dealer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dealer_proto_rawDesc), len(file_dealer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dealer_proto_goTypes,
		DependencyIndexes: file_dealer_proto_depIdxs,
		MessageInfos:      file_dealer_proto_msgTypes,
	}.Build()
	File_dealer_proto = out.File
	file_dealer_proto_goTypes = nil
	file_dealer_proto_depIdxs = nil
}
